-- Create the `User` table
CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    emailVtoken VARCHAR(255),
    isVerified BOOLEAN,
    passwordVtoken VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create the `Video` table with a foreign key referencing the `User` table
CREATE TABLE IF NOT EXISTS Videos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    Url VARCHAR(255) NOT NULL,
    video_name VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);
